Bachelors project/trading/trading-master/common/urls.py
from .views import IndexView, MonthlyReports, LoginView, LogoutView, RegisterView
from common.stock_logs import DailyStockLogs, MonthlyStockLogs
from django.urls import path
from product.views import ProductList

urlpatterns = [
    path('', ProductList.as_view(), name='index'),
    path('reports/monthly', MonthlyReports.as_view(), name='reports'),
    path('logs/daily', DailyStockLogs.as_view(), name='daily_logs'),
    path('logs/monthly', MonthlyStockLogs.as_view(), name='monthly_logs'),
    path('login', LoginView.as_view(), name='login'),
    path('register', RegisterView.as_view(), name='register'),
    path('logout', LogoutView.as_view(), name='logout'),
]

Bachelors project/trading/trading-master/customer/urls.py
from django.urls import path
from customer.views import (
    AddCustomer, CustomerList, UpdateCustomer,
    CustomerLedgerListView, DebitCustomerLedgerFormView,
    CreditCustomerLedgerFormView,
)

urlpatterns = [
    path('add/', AddCustomer.as_view(), name='add'),
    path('list/', CustomerList.as_view(), name='list'),
    path('update/<int:pk>/', UpdateCustomer.as_view(), name='update'),
    path(
        '<int:pk>/ledger/list/',
        CustomerLedgerListView.as_view(),
        name='ledger_list'
    ),
    path(
        '<int:pk>/ledger/debit/',
        DebitCustomerLedgerFormView.as_view(),
        name='ledger_debit'
    ),
    path(
        '<int:pk>/ledger/credit/',
        CreditCustomerLedgerFormView.as_view(),
        name='ledger_credit'
    ),
]

Bachelors project/trading/trading-master/expense/urls.py
from django.urls import path
from expense.views import (
    AddExpense, ExpenseList, DeleteExpense, UpdateExpense
)

urlpatterns = [
    path('add/', AddExpense.as_view(), name='add'),
    path('list/', ExpenseList.as_view(), name='list'),
    path('delete/<int:pk>/', DeleteExpense.as_view(), name='delete'),
    path('update/<int:pk>/', UpdateExpense.as_view(), name='update'),

]

Bachelors project/trading/trading-master/partum_trading/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('common.urls', 'common'), namespace='common')),
    path('product/', include(('product.urls', 'product'), namespace='product')),
    path('customer/', include(('customer.urls', 'customer'), namespace='customer')),
    path('expense/', include(('expense.urls', 'expense'), namespace='expense')),
    path('sales/', include(('sales.urls', 'sales'), namespace='sales')),
    path('bank_detail/', include(('banking_system.urls', 'bank'), namespace='bank')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Bachelors project/trading/trading-master/sales/urls.py
from sales.views import (
    InvoiceListView, CreateInvoiceTemplateView, ProductListAPIView,
    GenerateInvoiceAPIView, InvoiceDetailTemplateView, InvoiceInstallmentListView,
    InvoiceInstallmentFormView, InvoiceInstallmentDeleteView
)
from django.urls import path

urlpatterns = [
    path("invoices", InvoiceListView.as_view(), name='invoice_list'),
    path("invoice/create", CreateInvoiceTemplateView.as_view(), name='invoice_create'),
    path("invoice/<int:pk>/detail", InvoiceDetailTemplateView.as_view(), name='invoice_detail'),
    path("product/list/api/", ProductListAPIView.as_view(), name='product_list_api'),
    path("generate/invoice/api/", GenerateInvoiceAPIView.as_view(), name='generate_invoice_api'),

    path(
        "invoice/<int:invoice_id>/installments",
        InvoiceInstallmentListView.as_view(),
        name='installment_list'
    ),

    path(
        "invoice/<int:invoice_id>/installment/add",
        InvoiceInstallmentFormView.as_view(),
        name='installment_add'
    ),

    path(
        'installment/<int:pk>/delete',
        InvoiceInstallmentDeleteView.as_view(),
        name='installment_delete')
    ,
]

Bachelors project/trading/trading-master/customer/models.py
from django.db import models
from django.db.models import Sum
from django.utils import timezone


class Customer(models.Model):
    name = models.CharField(max_length=200)
    father_name = models.CharField(max_length=200, null=True, blank=True)
    cnic = models.CharField(max_length=200)
    mobile = models.CharField(max_length=200, null=True, blank=True)
    alternate_mobile = models.CharField(max_length=200, null=True, blank=True)
    resident = models.CharField(max_length=200, null=True, blank=True)
    address = models.CharField(max_length=200, null=True, blank=True)
    city = models.CharField(max_length=200, null=True, blank=True)
    date = models.DateField(default=timezone.now, null=True, blank=True)

    def __str__(self):
        return self.name

    def get_unpaid_amount(self):
        customer_ledgers = self.customer_ledger.all()

        if customer_ledgers:
            ledger_debit = customer_ledgers.aggregate(Sum('debit_amount'))
            ledger_credit = customer_ledgers.aggregate(Sum('credit_amount'))

            debit_amount = ledger_debit.get('debit_amount__sum')
            credit_amount = ledger_credit.get('credit_amount__sum')
        else:
            debit_amount = 0
            credit_amount = 0

        unpaid_amount = debit_amount - credit_amount
        return unpaid_amount


class CustomerLedger(models.Model):
    customer = models.ForeignKey(
        Customer, on_delete=models.CASCADE, related_name='customer_ledger'
    )
    invoice = models.ForeignKey(
        'sales.Invoice', related_name='invoice_ledger', blank=True, null=True, on_delete=models.CASCADE
    )
    debit_amount = models.DecimalField(
        max_digits=65, decimal_places=2, default=0, blank=True, null=True
    )
    credit_amount = models.DecimalField(
        max_digits=65, decimal_places=2, default=0, blank=True, null=True
    )
    details = models.TextField(max_length=500, blank=True, null=True)
    date = models.DateField(default=timezone.now, null=True, blank=True)

    def __str__(self):
        return self.customer.name

Bachelors project/trading/trading-master/templates/customer_ledger/credit.html
{% extends 'base.html' %}
{% block customer %}active{% endblock %}
{% block customer_list %}active{% endblock %}
{% block content %}
{% load staticfiles %}
<div class="content-wrapper">
    <section class="content-header">
        <ol class="breadcrumb">
            <li><a href="{% url 'common:index' %}"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="{% url 'customer:ledger_list' pk=customer.id %}">Ledger List</a></li>
            <li class="active">Credit/Payment</li>
        </ol>
    </section>
    <br>
    <section class="content">
        <div class="row">
            <div class="col-md-6 pull-left">
                <div class="box">
                    <div class="box-header">
                        <h3 class="text-center"><b>{{ customer.name|title }} |</b> <small><b>Credit Amount</b></small></h3>
                    </div>
                    <div class="box-body">
                        <form action="{% url 'customer:ledger_debit' pk=customer.id %}" method="post" autocomplete="off">
                            {% csrf_token %}
                            <input type="hidden" name="customer" value="{{ customer.id }}">
                            <div class="row">
                                <div class="col-md-12 pull-left form-group">
                                    <label class="form-control-label">Credit Amount <span style="color:red">*</span></label>
                                    <input type="text" name="credit_amount" class="form-control form-control-alternative" placeholder="Credit Amount" required>
                                </div>
                                <div class="col-md-12 pull-left form-group">
                                    <label class="form-control-label">Date <span style="color:red">*</span></label>
                                    <input type="date" name="date" class="form-control" required>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12 pull-left form-group">
                                    <label class="form-control-label">Details <span style="color:red">*</span></label>
                                    <textarea type="text" name="details" class="form-control form-control-alternative" placeholder="Details" required></textarea>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-4 pull-right form-group">
                                    <label class="form-control-label"></label>
                                    <button type="submit" value="Create" class="btn btn-primary form-control">Save</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>
{% endblock %}

Bachelors project/trading/trading-master/templates/customer_ledger/debit.html
{% extends 'base.html' %}
{% block customer %}active{% endblock %}
{% block customer_list %}active{% endblock %}
{% block content %}
{% load staticfiles %}
<div class="content-wrapper">
    <section class="content-header">
        <ol class="breadcrumb">
            <li><a href="{% url 'common:index' %}"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="{% url 'customer:ledger_list' pk=customer.id %}">Ledger List</a></li>
            <li class="active">Debit/Payment</li>
        </ol>
    </section>
    <br>
    <section class="content">
        <div class="row">
            <div class="col-md-6 pull-left">
                <div class="box">
                    <div class="box-header">
                        <h3 class="text-center"><b>{{ customer.name|title }} |</b> <small><b>Debit Amount</b></small></h3>
                    </div>
                    <div class="box-body">
                        <form action="{% url 'customer:ledger_debit' pk=customer.id %}" method="post" autocomplete="off">
                            {% csrf_token %}
                            <input type="hidden" name="customer" value="{{ customer.id }}">
                            <div class="row">
                                <div class="col-md-12 pull-left form-group">
                                    <label class="form-control-label">Debit Amount <span style="color:red">*</span></label>
                                    <input type="text" name="debit_amount" class="form-control form-control-alternative" placeholder="Debit Amount" required>
                                </div>
                                <div class="col-md-12 pull-left form-group">
                                    <label class="form-control-label">Date <span style="color:red">*</span></label>
                                    <input type="date" name="date" class="form-control" required>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12 pull-left form-group">
                                    <label class="form-control-label">Details <span style="color:red">*</span></label>
                                    <textarea type="text" name="details" class="form-control form-control-alternative" placeholder="Details" required></textarea>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-4 pull-right form-group">
                                    <label class="form-control-label"></label>
                                    <button type="submit" value="Create" class="btn btn-primary form-control">Save</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>
{% endblock %}

Bachelors project/trading/trading-master/templates/customer_ledger/ledger_list.html
{% extends 'base.html' %}
{% block customer %}active{% endblock %}
{% block customer_list %}active{% endblock %}
{% block content %}
{% load staticfiles %}
<div class="content-wrapper">
    <section class="content-header">
        <a href="{% url 'customer:ledger_debit' pk=customer.id %}"><button type="button" value="Create" class="btn btn-success">Add Ledger</button></a>
        <a href="{% url 'customer:ledger_credit' pk=customer.id %}"><button type="button" value="Create" class="btn btn-danger">Pay Ledger</button></a>
        <ol class="breadcrumb">
            <li><a href="{% url 'common:index' %}"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="{% url 'customer:list' %}"> Customer List</a></li>
            <li class="active">Ledger</li>
        </ol>
    </section>
    <section class="content">
        <div class="row">
            <div class="col-md-12">
                <div class="box">
                    <div class="box-header">
                        <h3 class="text-center"><b>{{ customer.name|title }} |</b> <small><b>Ledger Statement</b></small></h3>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <div class="col-md-4 pull-left">
                                <input type="date" class="form-control date_search" placeholder="Search by Date ..." >
                            </div>
                            <div class="col-md-2 pull-right">
                                <button class="form-control btn btn-primary search">Search</button>
                            </div>
                        <br><br>
                        <hr>
                        </div>
                    </div>
                    <div class="box-body">
                        <div class="table-responsive">
                            <table class="table align-items-center table-striped table-bordered table-hover">
                                <thead class="thead-dark">
                                <tr>
                                    <th>Date</th>
                                    <th>Detail</th>
                                    <th><small>Debit/Ledger Amount</small></th>
                                    <th><small>Credit/Payment Amount</small></th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for ledger in object_list %}
                                <tr>
                                    {% load humanize %}
                                    <td>{{ledger.date}}</td>
                                    <td>{{ledger.details}}</td>
                                    <td>{{ledger.debit_amount|floatformat:-2|intcomma }}</td>
                                    <td>{{ledger.credit_amount|floatformat:-2|intcomma }}</td>
                                </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                            {% if paginator.page_range|length > 1 %}
                            <div class="text-center col-lg-12">
                                <ul class="pagination justify-content-center">
                                    <li><a  style="background-color: #3070A8; color: white" class="page_previous" href="{% if page_obj.has_previous %}{% url 'customer:ledger_list' pk=customer.id %}?page={{ page_obj.previous_page_number }}{% else %}#{% endif %}" title="Previous"><<</a></li>
                                    <li><a style="background-color: #3070A8; color: white" class="page_next" href="{% if page_obj.has_next %}{% url 'customer:ledger_list' pk=customer.id %}?page={{ page_obj.next_page_number }}{% else %}#{% endif %}" title="Next">>></a></li>
                                </ul>
                            </div>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>
{% endblock %}

{% block script %}
    {{ block.super }}
<script>
$(function () {
    $('.search').on('click', function () {
        var url = '{% url "customer:ledger_list" pk=customer.id %}';
        window.location.href  = url + '?' + 'date=' + $('.date_search').val();
    });
})
</script>
{% endblock %}