Bachelors project/trading/trading-master/common/urls.py
from .views import IndexView, MonthlyReports, LoginView, LogoutView, RegisterView
from common.stock_logs import DailyStockLogs, MonthlyStockLogs
from django.urls import path
from product.views import ProductList

urlpatterns = [
    path('', ProductList.as_view(), name='index'),
    path('reports/monthly', MonthlyReports.as_view(), name='reports'),
    path('logs/daily', DailyStockLogs.as_view(), name='daily_logs'),
    path('logs/monthly', MonthlyStockLogs.as_view(), name='monthly_logs'),
    path('login', LoginView.as_view(), name='login'),
    path('register', RegisterView.as_view(), name='register'),
    path('logout', LogoutView.as_view(), name='logout'),
]

Bachelors project/trading/trading-master/expense/urls.py
from django.urls import path
from expense.views import (
    AddExpense, ExpenseList, DeleteExpense, UpdateExpense
)

urlpatterns = [
    path('add/', AddExpense.as_view(), name='add'),
    path('list/', ExpenseList.as_view(), name='list'),
    path('delete/<int:pk>/', DeleteExpense.as_view(), name='delete'),
    path('update/<int:pk>/', UpdateExpense.as_view(), name='update'),

]

Bachelors project/trading/trading-master/partum_trading/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('common.urls', 'common'), namespace='common')),
    path('product/', include(('product.urls', 'product'), namespace='product')),
    path('customer/', include(('customer.urls', 'customer'), namespace='customer')),
    path('expense/', include(('expense.urls', 'expense'), namespace='expense')),
    path('sales/', include(('sales.urls', 'sales'), namespace='sales')),
    path('bank_detail/', include(('banking_system.urls', 'bank'), namespace='bank')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Bachelors project/trading/trading-master/product/urls.py
from django.urls import path
from product.views import (
    AddProductCategory, AddProduct, UpdateProduct, ProductList,
    StockInProduct, StockOutProduct, StockInDetail, StockOutDetail
)

urlpatterns = [
    path('add/', AddProduct.as_view(), name='add'),
    path('add/category/',AddProductCategory.as_view(), name='add_category'),
    path('list/', ProductList.as_view(), name='list'),
    path('update/<int:pk>/', UpdateProduct.as_view(), name='update'),
    path('stock/item/<int:pk>/add', StockInProduct.as_view(), name='add_stock'),
    path('stock/item/<int:pk>/out', StockOutProduct.as_view(), name='stock_out'),
    path('stockin/item/<int:pk>/detail', StockInDetail.as_view(), name='stockin_detail'),
    path('stockout/item/<int:pk>/detail', StockOutDetail.as_view(), name='stockout_detail'),

]

Bachelors project/trading/trading-master/sales/urls.py
from sales.views import (
    InvoiceListView, CreateInvoiceTemplateView, ProductListAPIView,
    GenerateInvoiceAPIView, InvoiceDetailTemplateView, InvoiceInstallmentListView,
    InvoiceInstallmentFormView, InvoiceInstallmentDeleteView
)
from django.urls import path

urlpatterns = [
    path("invoices", InvoiceListView.as_view(), name='invoice_list'),
    path("invoice/create", CreateInvoiceTemplateView.as_view(), name='invoice_create'),
    path("invoice/<int:pk>/detail", InvoiceDetailTemplateView.as_view(), name='invoice_detail'),
    path("product/list/api/", ProductListAPIView.as_view(), name='product_list_api'),
    path("generate/invoice/api/", GenerateInvoiceAPIView.as_view(), name='generate_invoice_api'),

    path(
        "invoice/<int:invoice_id>/installments",
        InvoiceInstallmentListView.as_view(),
        name='installment_list'
    ),

    path(
        "invoice/<int:invoice_id>/installment/add",
        InvoiceInstallmentFormView.as_view(),
        name='installment_add'
    ),

    path(
        'installment/<int:pk>/delete',
        InvoiceInstallmentDeleteView.as_view(),
        name='installment_delete')
    ,
]

Bachelors project/trading/trading-master/expense/models.py
from django.db import models
from django.utils import timezone


class Expense(models.Model):
    amount = models.DecimalField(max_digits=65, decimal_places=2, default=0,
                                 null=True, blank=True)
    description = models.TextField(max_length=500, null=True, blank=True)
    date = models.DateField(default=timezone.now, null=True, blank=True)

    def __str__(self):
        return str(self.amount)

Bachelors project/trading/trading-master/templates/base.html
{% load static %}
{% load template_tags %}
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Abu Abeer al Gawabry Trading </title>
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <link rel="stylesheet" href="{% static 'bower_components/bootstrap/dist/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'bower_components/font-awesome/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'bower_components/Ionicons/css/ionicons.min.css' %}">
    <link rel="stylesheet" href="{% static 'bower_components/jvectormap/jquery-jvectormap.css' %}">
    <link rel="stylesheet" href="{% static 'dist/css/AdminLTE.min.css' %}">
    <link rel="stylesheet" href="{% static 'dist/css/skins/_all-skins.min.css' %}">

    <!-- Google Font -->
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>
<body class="hold-transition skin-blue sidebar-mini">
<div class="wrapper">

    <header class="main-header">

        <!-- Logo -->
        <a href="#" class="logo">
            <!-- mini logo for sidebar mini 50x50 pixels -->
            <span class="logo-mini"><b>Trading</b></span>
            <!-- logo for regular state and mobile devices -->
            <span class="logo-lg"><b>AAAG Trading</b></span>
        </a>

        <!-- Header Navbar: style can be found in header.less -->
        <nav class="navbar navbar-static-top">
            <!-- Sidebar toggle button-->
            <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
                <span class="sr-only">Toggle navigation</span>
            </a>
            <div  class="header">
                <span style="color:white;"><h4><b> Abu Abeer al Gawabry Trading</b></h4></span>
            </div>
            <!-- Navbar Right Menu -->
            <div class="navbar-custom-menu">
                <ul class="nav navbar-nav">
                   <!--  <li class="dropdown notifications-menu">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            Notifications <i class="fa fa-bell-o"></i>
                            <span class="label label-danger notification_count">10</span>
                        </a>
                        {% get_products as p_n %}
                        <ul class="dropdown-menu">
                            <li class="header">Lower Quantity Notifications</li>

                            <li class="header">
                                <table class="table table-bordered table-hover">
                                    {% for p in p_n %}
                                        {% if p.product_available_items <= p.notify_qty %}
                                            <tr>
                                                <th><strong>{{ p.name|title }}</strong></th>
                                                <td style="color:red">{{ p.product_available_items|floatformat:-2 }}</td>
                                            </tr>
                                        {% endif %}
                                    {% endfor %}
                                </table>
                            </li>
                            <li class="footer"><a href="{% url 'product:list' %}">View all</a></li>
                        </ul>
                    </li> -->
                </ul>
            </div>

        </nav>
    </header>
    <!-- Left side column. contains the logo and sidebar -->
    <aside class="main-sidebar">
        <!-- sidebar: style can be found in sidebar.less -->
        <section class="sidebar">
            <!-- search form -->
            <ul class="sidebar-menu" data-widget="tree">
                <li class="header">Main Navigation</li>
                <li class="treeview {% block product %}{% endblock %}">
                    <a href="#">
                        <i class="fa fa-product-hunt"></i> <span>Product</span>
                        <span class="pull-right-container">
                            <i class="fa fa-angle-left pull-right"></i>
                        </span>
                    </a>
                    <ul class="treeview-menu">
                        <li class="{% block add_category %}{% endblock %}"><a href="{% url 'product:add_category' %}"><i class="fa fa-circle-o"></i>Add Category</a></li>
                        <li class="{% block add_product %}{% endblock %}"><a href="{% url 'product:add' %}"><i class="fa fa-circle-o"></i>Add Product</a></li>
                        <li class="{% block product_list %}{% endblock %}"><a href="{% url 'product:list' %}"><i class="fa fa-circle-o"></i>List Products</a></li>
                    </ul>
                </li>
                <li class="treeview {% block customer %}{% endblock %}">
                    <a href="#">
                        <i class="fa fa-user"></i> <span>Customers</span>
                        <span class="pull-right-container">
                            <i class="fa fa-angle-left pull-right"></i>
                        </span>
                    </a>
                    <ul class="treeview-menu">
                        <li class="{% block customer_create %}{% endblock %}"><a href="{% url 'customer:add' %}"><i class="fa fa-circle-o"></i>Add Customer</a></li>
                        <li class="{% block customer_list %}{% endblock %}"><a href="{% url 'customer:list' %}"><i class="fa fa-circle-o"></i>Customer List</a></li>
                    </ul>
                </li>
                <li class="treeview {% block bank %}{% endblock %}">
                    <a href="#">
                        <i class="fa fa-university"></i> <span>Banking System</span>
                        <span class="pull-right-container">
                            <i class="fa fa-angle-left pull-right"></i>
                        </span>
                    </a>
                    <ul class="treeview-menu">
                        <li class="{% block add_bank %}{% endblock %}"><a href="{% url 'bank:add' %}"><i class="fa fa-circle-o"></i>Add Bank</a></li>
                        <li class="{% block bank_list %}{% endblock %}"><a href="{% url 'bank:list' %}"><i class="fa fa-circle-o"></i>Bank List</a></li>
                    </ul>
                </li>
                <li class="header">Sales & Expenses</li>
                <li class="treeview {% block expense %}{% endblock %}">
                    <a href="#">
                        <i class="fa fa-money"></i> <span>Expense System</span>
                        <span class="pull-right-container">
                            <i class="fa fa-angle-left pull-right"></i>
                        </span>
                    </a>
                    <ul class="treeview-menu">
                        <li class="{% block add_expense %}{% endblock %}"><a href="{% url 'expense:add' %}"><i class="fa fa-circle-o"></i> <span>Add Expense</span></a></li>
                        <li class="{% block expense_list %}{% endblock %}"><a href="{% url 'expense:list' %}"><i class="fa fa-circle-o"></i>Expense List</a></li>
                    </ul>
                </li>
                <li class="treeview {% block sales %}{% endblock %}">
                    <a href="#">
                        <i class="fa fa-shopping-cart"></i> <span>Sales</span>
                        <span class="pull-right-container">
                            <i class="fa fa-angle-left pull-right"></i>
                        </span>
                    </a>
                    <ul class="treeview-menu">
                        <li class="{% block create_invoice %}{% endblock %}"><a href="{% url 'sales:invoice_create' %}"><i class="fa fa-circle-o"></i> <span>Create Invoice</span></a></li>
                        <li class="{% block invoice_list %}{% endblock %}"><a href="{% url 'sales:invoice_list' %}"><i class="fa fa-circle-o"></i>Invoices List</a></li>
                    </ul>
                </li>
                <li class="header">Logs & Reports</li>
                <li class="treeview {% block stock_logs %}{% endblock %}">
                    <a href="#">
                        <i class="fa fa-history"></i> <span>Stock Logs</span>
                        <span class="pull-right-container">
                            <i class="fa fa-angle-left pull-right"></i>
                        </span>
                    </a>
                    <ul class="treeview-menu">
                        <li class="{% block daily_stock_logs %}{% endblock %}"><a href="{% url 'common:daily_logs' %}"><i class="fa fa-circle-o"></i> <span>Daily Logs</span></a></li>
                        <li class="{% block monthly_stock_logs %}{% endblock %}"><a href="{% url 'common:monthly_logs' %}"><i class="fa fa-circle-o"></i>Monthly Logs</a></li>
                    </ul>
                </li>
                <li class="treeview {% block reports %}{% endblock %}">
                    <a href="#">
                        <i class="fa fa-copy"></i> <span>Reports</span>
                        <span class="pull-right-container">
                            <i class="fa fa-angle-left pull-right"></i>
                        </span>
                    </a>
                    <ul class="treeview-menu">
                        <li class="{% block monthly_reports %}{% endblock %}"><a href="{% url 'common:reports' %}"><i class="fa fa-circle-o"></i> <span>Monthly Reports</span></a></li>
                    </ul>
                </li>
                <li class="header">User</li>
                 <li>
                    <a href="{% url 'common:logout' %}"><i class="fa fa-sign-out"></i> <span>Logout</span></a>
                </li>
                <li>
                    <a href="{% url 'admin:index' %}"><i class="fa fa-sign-in"></i> <span>Admin Pannel</span></a>
                </li>
            </ul>
        </section>
    </aside>

    <!-- Content Wrapper. Contains page content -->
    {% block content %}{% endblock %}
    <!-- /.content-wrapper -->

    <footer class="main-footer">
        <div class="pull-right hidden-xs">
            <b>Version</b> 2.4.18
        </div>
        <strong>Copyright &copy; 2022 <a href="#">Abu Abeer al Gawabry Trading</a>.</strong> All rights
        reserved.
    </footer>
</div>

{% block script %}
    <script src="{% static 'js/jquery.js' %}"></script>
    <script src="{% static 'js/jquery-1.8.3.min.js' %}"></script>
    <script src="{% static 'bower_components/jquery/dist/jquery.min.js' %}"></script>
    <script src="{% static 'bower_components/bootstrap/dist/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'bower_components/fastclick/lib/fastclick.js' %}"></script>
    <script src="{% static 'dist/js/adminlte.min.js' %}"></script>
    <script src="{% static 'bower_components/jquery-sparkline/dist/jquery.sparkline.min.js' %}"></script>
    <script src="{% static 'plugins/jvectormap/jquery-jvectormap-1.2.2.min.js' %}"></script>
    <script src="{% static 'plugins/jvectormap/jquery-jvectormap-world-mill-en.js' %}"></script>
    <script src="{% static 'bower_components/jquery-slimscroll/jquery.slimscroll.min.js' %}"></script>
    <script src="{% static 'bower_components/chart.js/Chart.js' %}"></script>
    <script src="{% static 'dist/js/demo.js' %}"></script>

    <script>
        var notification_count = 0;
        {% for p in p_n %}
            {% if p.product_available_items <= p.notify_qty %}
                    notification_count += 1;
            {% endif %}
        {% endfor %}

        $('.notification_count').text(notification_count);
    </script>

{% endblock %}
</body>
</html>

Bachelors project/trading/trading-master/templates/login.html
{% load static %}
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Log in</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.7 -->
    <link rel="stylesheet" href="{% static 'bower_components/bootstrap/dist/css/bootstrap.min.css' %}">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="{% static 'bower_components/font-awesome/css/font-awesome.min.css' %}">
    <!-- Ionicons -->
    <link rel="stylesheet" href="{% static 'bower_components/Ionicons/css/ionicons.min.css' %}">
    <!-- Theme style -->
    <link rel="stylesheet" href="{% static 'dist/css/AdminLTE.min.css' %}">
    <!-- iCheck -->
    <link rel="stylesheet" href="{% static 'plugins/iCheck/square/blue.css' %}">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->

    <!-- Google Font -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>
<body class="hold-transition login-page">
<div class="login-box">
    <div class="login-logo">
        <a href="#"><b>Abu Abeer al Gawabry Trading</b></a>
    </div>
    <!-- /.login-logo -->
    <div class="login-box-body">
        <p class="login-box-msg">Sign in to start your session</p>

        <form action="{% url 'common:login' %}" method="post">
            {% csrf_token %}
            <div class="form-group has-feedback">
                <input type="text" class="form-control" name="username" placeholder="Username">
                <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
            </div>
            <div class="form-group has-feedback">
                <input type="password" class="form-control" placeholder="Password" name="password">
                <span class="glyphicon glyphicon-lock form-control-feedback"></span>
            </div>
            <div class="row">
                <div class="col-xs-8">
                    <div class="checkbox icheck">
                        <label>
                            <input type="checkbox"> Remember Me
                        </label>
                    </div>
                </div>
                <!-- /.col -->
                <div class="col-xs-4">
                    <button type="submit" class="btn btn-primary btn-block btn-flat">Sign In</button>
                </div>
                <!-- /.col -->
            </div>
            <a href="{% url 'common:register' %}">register</a>
        </form>

<!--        <div class="social-auth-links text-center">-->
<!--            <p>- OR -</p>-->
<!--            <a href="#" class="btn btn-block btn-social btn-facebook btn-flat"><i class="fa fa-facebook"></i> Sign in using-->
<!--                Facebook</a>-->
<!--            <a href="#" class="btn btn-block btn-social btn-google btn-flat"><i class="fa fa-google-plus"></i> Sign in using-->
<!--                Google+</a>-->
<!--        </div>-->
        <!-- /.social-auth-links -->

<!--        <a href="#">I forgot my password</a><br>-->
<!--        <a href="#" class="text-center">Register a new membership</a>-->

    </div>
    <!-- /.login-box-body -->
</div>
<!-- /.login-box -->

<!-- jQuery 3 -->
<script src="{% static 'bower_components/jquery/dist/jquery.min.js' %}"></script>
<!-- Bootstrap 3.3.7 -->
<script src="{% static 'bower_components/bootstrap/dist/js/bootstrap.min.js' %}"></script>
<!-- iCheck -->
<script src="{% static 'plugins/iCheck/icheck.min.js' %}"></script>
<script>
    $(function () {
        $('input').iCheck({
            checkboxClass: 'icheckbox_square-blue',
            radioClass: 'iradio_square-blue',
            increaseArea: '20%' /* optional */
        });
    });
</script>
</body>
</html>

Bachelors project/trading/trading-master/templates/register.html
{% load static %}
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Register</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.7 -->
    <link rel="stylesheet" href="{% static 'bower_components/bootstrap/dist/css/bootstrap.min.css' %}">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="{% static 'bower_components/font-awesome/css/font-awesome.min.css' %}">
    <!-- Ionicons -->
    <link rel="stylesheet" href="{% static 'bower_components/Ionicons/css/ionicons.min.css' %}">
    <!-- Theme style -->
    <link rel="stylesheet" href="{% static 'dist/css/AdminLTE.min.css' %}">
    <!-- iCheck -->
    <link rel="stylesheet" href="{% static 'plugins/iCheck/square/blue.css' %}">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->

    <!-- Google Font -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>
<body class="hold-transition login-page">
<div class="login-box">
    <div class="login-logo">
        <a href="#"><b>Abu Abeer al Gawabry Trading</b></a>
    </div>
    <!-- /.login-logo -->
    <div class="login-box-body">
        <p class="login-box-msg">Sign in to start your session</p>

        <form class="form-login" method="post" action="{% url 'common:register' %}">
            <h2 class="form-login-heading">Registration Form</h2>
            <div class="login-wrap">
                {% if form.errors or form.non_field_errors %}
                    <div class="error-alert">
                        <i class="fa fa-warning pull-center"></i>
                    </div>
                {% endif %}
                {% csrf_token %}
                {% if form.non_field_errors %}
                    <div>
                        {{ form.non_field_errors }}
                    </div>
                {% endif %}
                <h5>Register yourself Free!</h5>
                 <input type="text" class="form-control" placeholder="First Name" name="firstname" autofocus><br>
                  <input type="text" class="form-control" placeholder="Last Name" name="lastname" autofocus><br>
                  <input type="email" class="form-control" placeholder="Email" name="email" autofocus><br>
                  <input type="text" class="form-control" placeholder="Phone" name="email" placeholder="eg:+968-9xxxxxxx"  minlength="10" autofocus><br>
                <input type="text" class="form-control" placeholder="Username" name="username" value="{{ username }}" autofocus>
                {% if form.errors %}
                    {{ form.errors.username }}
                {% endif %}
                <br>
                <input type="password" class="form-control" name="password1" placeholder="Password" value="{{ password1 }}">
                {% if form.errors %}
                    {{ form.errors.password1  }}
                {% endif %}
                <br>
                <input type="password" class="form-control" name="password2" placeholder="Confirm Password" value="{{ password2 }}">
                {% if form.errors %}
                    {{ form.errors.password2  }}
                {% endif %}
                <br>
                <button class="btn btn-primary btn-block" type="submit"><i class="fa fa-lock"></i> Register</button>
            </div>
        </form>

<!--        <div class="social-auth-links text-center">-->
<!--            <p>- OR -</p>-->
<!--            <a href="#" class="btn btn-block btn-social btn-facebook btn-flat"><i class="fa fa-facebook"></i> Sign in using-->
<!--                Facebook</a>-->
<!--            <a href="#" class="btn btn-block btn-social btn-google btn-flat"><i class="fa fa-google-plus"></i> Sign in using-->
<!--                Google+</a>-->
<!--        </div>-->
        <!-- /.social-auth-links -->

<!--        <a href="#">I forgot my password</a><br>-->
<!--        <a href="#" class="text-center">Register a new membership</a>-->

    </div>
    <!-- /.login-box-body -->
</div>
<!-- /.login-box -->

<!-- jQuery 3 -->
<script src="{% static 'bower_components/jquery/dist/jquery.min.js' %}"></script>
<!-- Bootstrap 3.3.7 -->
<script src="{% static 'bower_components/bootstrap/dist/js/bootstrap.min.js' %}"></script>
<!-- iCheck -->
<script src="{% static 'plugins/iCheck/icheck.min.js' %}"></script>
<script>
    $(function () {
        $('input').iCheck({
            checkboxClass: 'icheckbox_square-blue',
            radioClass: 'iradio_square-blue',
            increaseArea: '20%' /* optional */
        });
    });
</script>
</body>
</html>