Bachelors project/trading/trading-master/common/urls.py
from .views import IndexView, MonthlyReports, LoginView, LogoutView, RegisterView
from common.stock_logs import DailyStockLogs, MonthlyStockLogs
from django.urls import path
from product.views import ProductList

urlpatterns = [
    path('', ProductList.as_view(), name='index'),
    path('reports/monthly', MonthlyReports.as_view(), name='reports'),
    path('logs/daily', DailyStockLogs.as_view(), name='daily_logs'),
    path('logs/monthly', MonthlyStockLogs.as_view(), name='monthly_logs'),
    path('login', LoginView.as_view(), name='login'),
    path('register', RegisterView.as_view(), name='register'),
    path('logout', LogoutView.as_view(), name='logout'),
]

Bachelors project/trading/trading-master/partum_trading/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('common.urls', 'common'), namespace='common')),
    path('product/', include(('product.urls', 'product'), namespace='product')),
    path('customer/', include(('customer.urls', 'customer'), namespace='customer')),
    path('expense/', include(('expense.urls', 'expense'), namespace='expense')),
    path('sales/', include(('sales.urls', 'sales'), namespace='sales')),
    path('bank_detail/', include(('banking_system.urls', 'bank'), namespace='bank')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Bachelors project/trading/trading-master/sales/urls.py
from sales.views import (
    InvoiceListView, CreateInvoiceTemplateView, ProductListAPIView,
    GenerateInvoiceAPIView, InvoiceDetailTemplateView, InvoiceInstallmentListView,
    InvoiceInstallmentFormView, InvoiceInstallmentDeleteView
)
from django.urls import path

urlpatterns = [
    path("invoices", InvoiceListView.as_view(), name='invoice_list'),
    path("invoice/create", CreateInvoiceTemplateView.as_view(), name='invoice_create'),
    path("invoice/<int:pk>/detail", InvoiceDetailTemplateView.as_view(), name='invoice_detail'),
    path("product/list/api/", ProductListAPIView.as_view(), name='product_list_api'),
    path("generate/invoice/api/", GenerateInvoiceAPIView.as_view(), name='generate_invoice_api'),

    path(
        "invoice/<int:invoice_id>/installments",
        InvoiceInstallmentListView.as_view(),
        name='installment_list'
    ),

    path(
        "invoice/<int:invoice_id>/installment/add",
        InvoiceInstallmentFormView.as_view(),
        name='installment_add'
    ),

    path(
        'installment/<int:pk>/delete',
        InvoiceInstallmentDeleteView.as_view(),
        name='installment_delete')
    ,
]

Bachelors project/trading/trading-master/sales/models.py
from django.db import models
from django.db.models import Sum
from django.utils import timezone


class Invoice(models.Model):

    PAYMENT_CASH = 'Cash'
    PAYMENT_INSTALLMENT = 'Installment'
    PAYMENT_CHECK = 'Check'

    PAYMENT_TYPES = (
        (PAYMENT_CASH, 'Cash'),
        (PAYMENT_INSTALLMENT, 'Installment'),
        (PAYMENT_CHECK, 'Check'),
    )

    customer = models.ForeignKey(
        'customer.Customer',
        related_name='customer_sales',
        blank=True, null=True, on_delete=models.SET_NULL
    )

    payment_type = models.CharField(
        choices=PAYMENT_TYPES, default=PAYMENT_CASH, max_length=100)

    bank_details = models.ForeignKey(
        'banking_system.Bank', related_name='bank_detail_payments',
        blank=True, null=True, on_delete=models.SET_NULL
    )

    total_quantity = models.CharField(
        max_length=10, blank=True, null=True, default=1
    )

    sub_total = models.DecimalField(
        max_digits=65, decimal_places=2, default=0, blank=True, null=True
    )

    paid_amount = models.DecimalField(
        max_digits=65, decimal_places=2, default=0, blank=True, null=True
    )

    remaining_payment = models.DecimalField(
        max_digits=65, decimal_places=2, default=0, blank=True, null=True
    )

    discount = models.DecimalField(
        max_digits=65, decimal_places=2, default=0, blank=True, null=True
    )

    shipping = models.DecimalField(
        max_digits=65, decimal_places=2, default=0, blank=True, null=True
    )

    grand_total = models.DecimalField(
        max_digits=65, decimal_places=2, default=0, blank=True, null=True
    )

    cash_payment = models.DecimalField(
        max_digits=65, decimal_places=2, default=0, blank=True, null=True
    )

    cash_returned = models.DecimalField(
        max_digits=65, decimal_places=2, default=0, blank=True, null=True
    )
    date = models.DateField(default=timezone.now, blank=True, null=True)

    def __str__(self):
        return str(self.id).zfill(7)

    def is_installment(self):
        invoice_installments = InvoiceInstallment.objects.filter(
            invoice__id=self.id)

        grand_total = self.grand_total

        if invoice_installments.exists():
            total_paid_amount = invoice_installments.aggregate(
                Sum('paid_amount'))
            total_paid_amount = float(
                total_paid_amount.get('paid_amount__sum') or 0
            )

        else:
            total_paid_amount = 0

        if float(grand_total) <= total_paid_amount:
            return True

        return False

    def remaining_installment(self):
        invoice_installments = InvoiceInstallment.objects.filter(
            invoice__id=self.id)

        grand_total = self.grand_total

        if invoice_installments.exists():
            total_paid_amount = invoice_installments.aggregate(
                Sum('paid_amount'))
            total_paid_amount = float(
                total_paid_amount.get('paid_amount__sum') or 0
            )

        else:
            total_paid_amount = 0

        return float(grand_total) - total_paid_amount

    def has_installment(self):
        if self.invoice_installment.all().exists():
            return True

        return False




class InvoiceInstallment(models.Model):
    invoice = models.ForeignKey(
        Invoice, related_name='invoice_installment', on_delete=models.CASCADE)
    paid_amount = models.DecimalField(
        max_digits=65, decimal_places=2, default=0, blank=True, null=True
    )
    description = models.TextField(blank=True, null=True)
    date = models.DateField(
        default=timezone.now, blank=True, null=True)

    def __str__(self):
        return (
            '%s Installment' % self.invoice.customer.name if
            self.invoice.customer else ''
        )

Bachelors project/trading/trading-master/sales/forms.py
from django import forms
from sales.models import Invoice, InvoiceInstallment


class InvoiceForm(forms.ModelForm):
    class Meta:
        model = Invoice
        fields = '__all__'


class InvoiceInstallmentForm(forms.ModelForm):
    class Meta:
        model = InvoiceInstallment
        fields = '__all__'

Bachelors project/trading/trading-master/sales/views.py
import json
from django.core.paginator import Paginator
from django.views.generic import (
    ListView, TemplateView, View, FormView, DeleteView)
from django.http import JsonResponse
from django.db.models import Sum
from django.utils import timezone
from django.views.decorators.csrf import csrf_exempt, csrf_protect
from django.db import transaction
from django.shortcuts import render
from customer.models import Customer
from product.models import Product
from sales.models import Invoice, InvoiceInstallment
from django.http import HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from customer.forms import CustomerForm, CustomerLedgerForm
from product.forms import ProductForm, StockOutForm, PurchasedItemForm
from sales.forms import InvoiceForm, InvoiceInstallmentForm
from banking_system.models import Bank
from banking_system.forms import BankDetailForm


class InvoiceListView(ListView):
    template_name = 'sales/invoice_list.html'
    model = Invoice
    paginate_by = 100

    def dispatch(self, request, *args, **kwargs):
        if not self.request.user.is_authenticated:
            return HttpResponseRedirect(reverse('common:login'))

        return super(
            InvoiceListView, self).dispatch(request, *args, **kwargs)

    def get_queryset(self):
        queryset = self.queryset
        if not queryset:
            queryset = Invoice.objects.all().order_by('-id')

        if self.request.GET.get('customer_name'):
            queryset = queryset.filter(
                customer__name__contains=self.request.GET.get('customer_name'))

        if self.request.GET.get('customer_id'):
            queryset = queryset.filter(
                id=self.request.GET.get('customer_id').lstrip('0')
            )

        if self.request.GET.get('date'):
            queryset = queryset.filter(
                date=self.request.GET.get('date')
            )

        return queryset.order_by('-id')


class CreateInvoiceTemplateView(TemplateView):
    template_name = 'sales/create_invoice.html'

    def dispatch(self, request, *args, **kwargs):
        if not self.request.user.is_authenticated:
            return HttpResponseRedirect(reverse('common:login'))

        return super(
            CreateInvoiceTemplateView, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(CreateInvoiceTemplateView, self).get_context_data(**kwargs)
        context.update({
            'customers': Customer.objects.all().order_by('name'),
            'products': Product.objects.all().order_by('name'),
            'today_date': timezone.now().date(),
            'banks': Bank.objects.all().order_by('name')
        })
        return context


class ProductListAPIView(View):

    def dispatch(self, request, *args, **kwargs):
        if not self.request.user.is_authenticated:
            return HttpResponseRedirect(reverse('common:login'))

        return super(
            ProductListAPIView, self).dispatch(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        products = Product.objects.all()
        items = []

        for product in products:
            p = {
                'id': product.id,
                'name': product.name,
                'category_name': product.category.category,
            }

            if product.stockin_product.exists():
                stock_detail = product.stockin_product.all().latest('id')
                p.update({
                    'selling_price': '%g' % stock_detail.price_per_item,
                    'buying_price': '%g' % stock_detail.buying_price_item,
                })

                all_stock = product.stockin_product.all()
                if all_stock:
                    all_stock = all_stock.aggregate(Sum('stock_quantity'))
                    all_stock = float(all_stock.get('stock_quantity__sum') or 0)
                else:
                    all_stock = 0

                purchased_stock = product.stockout_product.all()
                if purchased_stock:
                    purchased_stock = purchased_stock.aggregate(
                        Sum('stock_out_quantity'))
                    purchased_stock = float(
                        purchased_stock.get('stock_out_quantity__sum') or 0)
                else:
                    purchased_stock = 0

                p.update({
                    'stock': all_stock - purchased_stock
                })

            else:
                p.update(
                    {
                        'selling_item': 0,
                        'buying_price': 0
                    }
                )

            items.append(p)

        return JsonResponse({'products': items})


class GenerateInvoiceAPIView(View):

    def dispatch(self, request, *args, **kwargs):
        if not self.request.user.is_authenticated:
            return HttpResponseRedirect(reverse('common:login'))

        return super(
            GenerateInvoiceAPIView, self).dispatch(request, *args, **kwargs)

    @csrf_exempt
    def dispatch(self, request, *args, **kwargs):
        return super(GenerateInvoiceAPIView, self).dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        customer_name = self.request.POST.get('customer_name')
        customer_phone = self.request.POST.get('customer_phone')
        customer_cnic = self.request.POST.get('customer_cnic')
        sub_total = self.request.POST.get('sub_total')
        discount = self.request.POST.get('discount')
        shipping = self.request.POST.get('shipping')
        grand_total = self.request.POST.get('grand_total')
        totalQty = self.request.POST.get('totalQty')
        remaining_payment = self.request.POST.get('remaining_amount')
        paid_amount = self.request.POST.get('paid_amount')
        cash_payment = self.request.POST.get('cash_payment')
        returned_cash = self.request.POST.get('returned_cash')
        payment_type = self.request.POST.get('payment_type')
        bank = self.request.POST.get('bank')
        items = json.loads(self.request.POST.get('items'))

        with transaction.atomic():
            invoice_form_kwargs = {
                'discount': discount,
                'grand_total': grand_total,
                'total_quantity': totalQty,
                'shipping': shipping,
                'paid_amount': paid_amount,
                'remaining_payment': remaining_payment,
                'cash_payment': cash_payment,
                'returned_payment': returned_cash,
                'payment_type': payment_type,
            }
            invoice_form = InvoiceForm(invoice_form_kwargs)
            invoice = invoice_form.save()

            if self.request.POST.get('customer_id'):
                customer_id = self.request.POST.get('customer_id')
                customer = Customer.objects.get(id=customer_id)
            else:
                customer_form_kwargs = {
                    'name': customer_name,
                    'cnic': customer_cnic,
                    'mobile': customer_phone,
                }
                customer_form = CustomerForm(customer_form_kwargs)
                if customer_form.is_valid():
                    customer = customer_form.save()
                    customer_id = customer.id
                else:
                    customer_id = ''

            if customer_id:
                invoice.customer = customer
                invoice.save()

            for item in items:
                product = Product.objects.get(id=item.get('item_id'))
                latest_stockin = product.stockin_product.all().latest('id')

                stock_out_kwargs = {
                    'product': product.id,
                    'invoice': invoice.id,
                    'stock_out_quantity': float(item.get('qty')),
                    'buying_price': (
                            float(latest_stockin.buying_price_item) *
                            float(item.get('qty'))),
                    'selling_price': (
                            float(item.get('price')) * float(item.get('qty'))),
                    'date': timezone.now().date()
                }
                stock_out = StockOutForm(stock_out_kwargs)
                stock_out.save()

                purchased_item_kwargs = {
                    'item': product.id,
                    'invoice': invoice.id,
                    'quantity': item.get('qty'),
                    'price': item.get('price'),
                    'purchase_amount': item.get('total'),
                }
                purchase_item = PurchasedItemForm(purchased_item_kwargs)
                purchase_item.save()

            if customer_id or self.request.POST.get('customer_id'):
                if payment_type == 'Installment':
                    installment_kwargs = {
                        'invoice': invoice.id,
                        'paid_amount': paid_amount,
                        'description': 'Advance Payment'

                    }
                    installment__form = InvoiceInstallmentForm(
                        installment_kwargs)
                    installment__form.save()

                elif float(remaining_payment):

                    ledger_form_kwargs = {
                        'customer': customer_id,
                        'invoice': invoice.id,
                        'debit_amount': remaining_payment,
                        'details': (
                                'Remaining Payment for Bill/Receipt No %s '
                                % str(invoice.id).zfill(7)),
                        'date': timezone.now()
                    }

                    customer_ledger = CustomerLedgerForm(ledger_form_kwargs)
                    customer_ledger.save()

            if payment_type == 'Check':
                bank_details_kwargs = {
                    'bank': bank,
                    'invoice': invoice.id,
                    'credit': paid_amount,

Bachelors project/trading/trading-master/templates/sales/installment_add.html
{% extends 'base.html' %}
{% block sales %}active{% endblock %}
{% block invoice_list %}active{% endblock %}

{% block content %}
{% load staticfiles %}
<div class="content-wrapper">
    <section class="content-header">
        <ol class="breadcrumb">
            <li><a href="{% url 'common:index' %}"><i class="fa fa-dashboard"></i> Home</a></li>
            <li class="active">Add Installment</li>
        </ol>
    </section>
    <br>
    <section class="content">
        <div class="row">
            <div class="col-md-6 pull-left">
                <div class="box">
                    <div class="box-header">
                        <h3 class="text-center"><b>Add Installment</b></h3>
                    </div>
                    <div class="box-body">
                        <form action="{% url 'sales:installment_add' invoice_id=invoice.id  %}" method="post" autocomplete="off">
                            {% csrf_token %}
                            <input type="hidden" name="invoice" class="form-control form-control-alternative" value="{{ invoice.id }}">

                            <div class="row">
                                <div class="col-md-6 pull-left form-group">
                                    Customer Name: <strong>{{ invoice.customer.name|title }}</strong>
                                </div>
                                <div class="col-md-6 pull-left form-group">
                                    Item: <strong>{{ invoice.invoice_purchased.all.0|title }}</strong>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-12 pull-left form-group">
                                    <label class="form-control-label">Amount <span style="color:red">*</span></label>
                                    <input type="text" name="paid_amount" class="form-control form-control-alternative" placeholder="Amount" required>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12 pull-left form-group">
                                    <label class="form-control-label">Date <span style="color:red">*</span></label>
                                    <input type="date" name="date" class="form-control form-control-alternative" placeholder="Date" onfocus="(this.type='date')" onblur="(this.type='text')" required>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12 pull-left form-group">
                                    <label class="form-control-label">Description <span style="color:red">*</span></label>
                                    <input type="text" name="description" class="form-control form-control-alternative" placeholder="Description" required>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-4 pull-right form-group">
                                    <label class="form-control-label"></label>
                                    <button type="submit" value="Create" class="btn btn-primary form-control">Save</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>

{% endblock %}

Bachelors project/trading/trading-master/templates/sales/installment_list.html
{% extends 'base.html' %}
{% block sales %}active{% endblock %}
{% block invoice_list %}active{% endblock %}
{% block content %}

    <div class="content-wrapper">
    <section class="content-header">
        <a href="{% url 'sales:invoice_detail' pk=invoice_id %}"><button type="button" id="invoice" class="btn btn-primary" >View Invoice</button></a>
        <a href="{% url 'sales:installment_add' invoice_id=invoice_id %}"><button type="button" id="invoice" class="btn btn-primary">Add Installment</button></a>
        <ol class="breadcrumb">
            <li><a href="{% url 'common:index' %}"><i class="fa fa-dashboard"></i>Home</a></li>
            <li><a href="{% url 'sales:invoice_list' %}">View Invoice</a></li>
            <li class="active">Installments</li>
        </ol>
    </section>
    <section class="content">
        <div class="row">
            <div class="col-md-12">
                <div class="box">
                    <div class="box-header">
                        <h3 class="text-center "><b>Installments</b></h3>
                    </div>
                    <div class="box-body">
                        <div class="table-responsive">
                            <div class="text-right">
                                Total Installment Paid: <strong>{{ total_paid_amount|floatformat:-2 }}</strong><br>
                                Remaining Installments: <strong>{{ remaining_amount|floatformat:-2 }}</strong><br>
                            </div>
                            <table class="table align-items-center table-striped table-bordered table-hover">
                                <thead class="thead-dark">
                                    <tr>
                                        <th>Date</th>
                                        <th>Invoice</th>
                                        <th>Customer</th>
                                        <th>Paid Amount</th>
                                        <th>Description</th>
                                        <th class="text-center">Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                {% if not object_list %}
                                    <tr><td colspan="7" class="text-center">No Installment Found!</td></tr>
                                {% endif %}
                                {% for installment in object_list %}
                                    <tr>
                                        {% load humanize %}
                                        <td>{{ installment.date }}</td>
                                        <td>{{ installment.invoice.id|stringformat:"07d" }}</td>
                                        <td>{{ installment.invoice.customer.name|title }}</td>
                                        <td>{{ installment.paid_amount|floatformat:-2|intcomma }}</td>
                                        <td>{{ installment.description }}</td>
                                        <td class="text-center">
                                            <a href="{% url 'sales:installment_delete' pk=installment.id %}"><button class="btn btn-danger btn-xs">Delete</button></a>
                                        </td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                            {% if paginator.page_range|length > 1 %}
                                <div class="text-center">
                                    <ul class="pagination">
                                        <li><a  style="background-color: #3070A8; color: white" class="page_previous" href="{% if page_obj.has_previous %}{% url 'sales:invoice_list' %}?page={{ page_obj.previous_page_number }}{% else %}#{% endif %}" title="Previous"><<</a></li>
                                        <li><a style="background-color: #3070A8; color: white" class="page_next" href="{% if page_obj.has_next %}{% url 'sales:invoice_list' %}?page={{ page_obj.next_page_number }}{% else %}#{% endif %}" title="Next">>></a></li>
                                    </ul>
                                </div>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>
{% endblock %}

Bachelors project/trading/trading-master/templates/sales/invoice_list.html
{% extends 'base.html' %}
{% block sales %}active{% endblock %}
{% block invoice_list %}active{% endblock %}
{% block content %}

    <div class="content-wrapper">
    <section class="content-header">
        <ol class="breadcrumb">
            <li><a href="{% url 'common:index' %}"><i class="fa fa-dashboard"></i>Home</a></li>
            <li class="active">Invoice List</li>
        </ol>
    </section>
    <br>
    <section class="content">
        <div class="row">
            <div class="col-md-12">
                <div class="box">
                    <div class="box-header">
                        <h3 class="text-center "><b>Invoice List</b></h3>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <div class="col-md-3 pull-left">
                                <input type="text" class="form-control name_search" placeholder="Search by Name ..." >
                            </div>
                            <div class="col-md-3">
                                <input type="text" class="form-control id_search" placeholder="Search by Invoice No ...">
                            </div>
                            <div class="col-md-3">
                                <input type="date" class="form-control date_search" placeholder="Search by Date ...">
                            </div>
                            <div class="col-md-2 pull-right">
                                <button class="form-control btn btn-primary search">Search</button>
                            </div>
                        </div>
                    </div>
                    <hr>
                    <div class="box-body">
                        <div class="table-responsive">
                            <table class="table align-items-center table-striped table-bordered table-hover">
                                <thead class="thead-dark">
                                    <tr>
                                        <th>Date</th>
                                        <th>Invoice</th>
                                        <th>Customer</th>
                                        <th>Payment</th>
                                        <th>Installment</th>
                                        <th>Quantity</th>
                                        <th>Sub Total</th>
                                        <th>Grand Total</th>
                                        <th class="text-center">Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                {% if not object_list %}
                                    <tr><td colspan="7" class="text-center">No Invoices Found!</td></tr>
                                {% endif %}
                                {% for invoice in object_list %}
                                    <tr>
                                        {% load humanize %}
                                        <td>{{ invoice.date }}</td>
                                        <td>{{ invoice.id|stringformat:"07d" }}</td>
                                        <td>{{ invoice.customer.name|title }}</td>
                                        <td>{{ invoice.payment_type }}</td>
                                        {% if invoice.has_installment  %}
                                            <td>{% if invoice.is_installment %}<i class="fa fa-check-circle" style="color: #439D44"></i>{% else %}<i class="fa fa-times-circle" style="color: #C9312C"></i>{% endif %}</td>
                                        {% else %}
                                            <td>-</td>
                                        {% endif %}
                                        <td>{{ invoice.total_quantity|floatformat:-2|intcomma }}</td>
                                        <td>{{ invoice.sub_total|floatformat:-2|intcomma }}</td>
                                        <td>{{ invoice.grand_total|floatformat:-2|intcomma }}</td>
                                        <td class="text-center">
                                            <a href="{% url 'sales:invoice_detail' pk=invoice.id %}"><button class="btn btn-primary btn-xs">View</button></a>
                                            {% if invoice.has_installment %}
                                                <a href="{% url 'sales:installment_list' invoice_id=invoice.id %}"><button class="btn btn-warning btn-xs">Installments</button></a>
                                            {% else %}
                                                <button class="btn default btn-xs">Not Available</button>
                                            {% endif %}
                                        </td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                            {% if paginator.page_range|length > 1 %}
                                <div class="text-center">
                                    <ul class="pagination">
                                        <li><a  style="background-color: #3070A8; color: white" class="page_previous" href="{% if page_obj.has_previous %}{% url 'sales:invoice_list' %}?page={{ page_obj.previous_page_number }}{% else %}#{% endif %}" title="Previous"><<</a></li>
                                        <li><a style="background-color: #3070A8; color: white" class="page_next" href="{% if page_obj.has_next %}{% url 'sales:invoice_list' %}?page={{ page_obj.next_page_number }}{% else %}#{% endif %}" title="Next">>></a></li>
                                    </ul>
                                </div>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>
{% endblock %}

{% block script %}
    {{ block.super }}
<script>
$(function () {
    $('.search').on('click', function () {
        var url = '{% url "sales:invoice_list" %}';
        window.location.href  = url + '?' + 'customer_name=' + $('.name_search').val() + '&customer_id=' +  $('.id_search').val() + '&date=' +  $('.date_search').val();
    });
})
</script>

<script>
$('#invoice').on('click', function() {
    var $this = $(this);
  $this.button('loading');
    setTimeout(function() {
       $this.button('reset');
   }, 5000);
});

</script>
{% endblock %}