Bachelors project/trading/trading-master/banking_system/urls.py
from django.urls import path
from banking_system.views import (
    AddBankFormView, BankListView, BankDetailListView, AddBankUpdateView,
    CreditBankFormView, CreditBankUpdateView, DebitBankFormView, DebitBankUpdateView
)

urlpatterns = [
    path('add/', AddBankFormView.as_view(), name='add'),
    path('list/', BankListView.as_view(), name='list'),
    path('detail_list/<int:pk>/', BankDetailListView.as_view(), name='detail_list'),
    path('update/<int:pk>/', AddBankUpdateView.as_view(), name='update'),
    path('credit/<int:pk>/', CreditBankFormView.as_view(), name='credit'),
    path('credit/update/<int:pk>/', CreditBankUpdateView.as_view(), name='credit_update'),
    path('debit/<int:pk>/', DebitBankFormView.as_view(), name='debit'),
    path('debit/update/<int:pk>/', DebitBankUpdateView.as_view(), name='debit_update'),

]

Bachelors project/trading/trading-master/common/urls.py
from .views import IndexView, MonthlyReports, LoginView, LogoutView, RegisterView
from common.stock_logs import DailyStockLogs, MonthlyStockLogs
from django.urls import path
from product.views import ProductList

urlpatterns = [
    path('', ProductList.as_view(), name='index'),
    path('reports/monthly', MonthlyReports.as_view(), name='reports'),
    path('logs/daily', DailyStockLogs.as_view(), name='daily_logs'),
    path('logs/monthly', MonthlyStockLogs.as_view(), name='monthly_logs'),
    path('login', LoginView.as_view(), name='login'),
    path('register', RegisterView.as_view(), name='register'),
    path('logout', LogoutView.as_view(), name='logout'),
]

Bachelors project/trading/trading-master/expense/urls.py
from django.urls import path
from expense.views import (
    AddExpense, ExpenseList, DeleteExpense, UpdateExpense
)

urlpatterns = [
    path('add/', AddExpense.as_view(), name='add'),
    path('list/', ExpenseList.as_view(), name='list'),
    path('delete/<int:pk>/', DeleteExpense.as_view(), name='delete'),
    path('update/<int:pk>/', UpdateExpense.as_view(), name='update'),

]

Bachelors project/trading/trading-master/partum_trading/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('common.urls', 'common'), namespace='common')),
    path('product/', include(('product.urls', 'product'), namespace='product')),
    path('customer/', include(('customer.urls', 'customer'), namespace='customer')),
    path('expense/', include(('expense.urls', 'expense'), namespace='expense')),
    path('sales/', include(('sales.urls', 'sales'), namespace='sales')),
    path('bank_detail/', include(('banking_system.urls', 'bank'), namespace='bank')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Bachelors project/trading/trading-master/sales/urls.py
from sales.views import (
    InvoiceListView, CreateInvoiceTemplateView, ProductListAPIView,
    GenerateInvoiceAPIView, InvoiceDetailTemplateView, InvoiceInstallmentListView,
    InvoiceInstallmentFormView, InvoiceInstallmentDeleteView
)
from django.urls import path

urlpatterns = [
    path("invoices", InvoiceListView.as_view(), name='invoice_list'),
    path("invoice/create", CreateInvoiceTemplateView.as_view(), name='invoice_create'),
    path("invoice/<int:pk>/detail", InvoiceDetailTemplateView.as_view(), name='invoice_detail'),
    path("product/list/api/", ProductListAPIView.as_view(), name='product_list_api'),
    path("generate/invoice/api/", GenerateInvoiceAPIView.as_view(), name='generate_invoice_api'),

    path(
        "invoice/<int:invoice_id>/installments",
        InvoiceInstallmentListView.as_view(),
        name='installment_list'
    ),

    path(
        "invoice/<int:invoice_id>/installment/add",
        InvoiceInstallmentFormView.as_view(),
        name='installment_add'
    ),

    path(
        'installment/<int:pk>/delete',
        InvoiceInstallmentDeleteView.as_view(),
        name='installment_delete')
    ,
]

Bachelors project/trading/trading-master/templates/banking/add_bank.html
{% extends 'base.html' %}
{% block bank %}active{% endblock %}
{% block add_bank %}avtive{% endblock %}
{% block content %}
{% load staticfiles %}

<div class="content-wrapper">
    <section class="content-header">
        <ol class="breadcrumb">
            <li><a href="{% url 'common:index' %}"><i class="fa fa-dashboard"></i> Home</a></li>
            <li class="active">Add Bank</li>
        </ol>
    </section>
    <br>
    <section class="content">
        <div class="row">
            <div class="col-md-6 pull-left">
                <div class="box">
                    <div class="box-header">
                        <h3 class="text-center"><b>Add Bank</b></h3>
                    </div>
                    <div class="box-body">
                        <form action="{% url 'bank:add' %}" method="post" autocomplete="off">
                            {% csrf_token %}
                            <div class="row">
                                <div class="col-md-12 pull-left form-group">
                                    <label class="form-control-label">Bank Name <span style="color:red">*</span></label>
                                    <input type="text" name="name" class="form-control form-control-alternative" placeholder="Bank Name" required>
                                </div>
                                <div class="col-md-12 pull-left form-group">
                                    <label class="form-control-label">Bank Branch <span style="color:red">*</span></label>
                                    <input type="text" name="branch" class="form-control form-control-alternative" placeholder="Bank Branch" required>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12 pull-left form-group">
                                    <label class="form-control-label">Account Number <span style="color:red">*</span></label>
                                    <input type="text" name="account_number" class="form-control form-control-alternative" placeholder="Account Number" required>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-4 pull-right form-group">
                                    <label class="form-control-label"></label>
                                    <button type="submit" value="Create" class="btn btn-primary form-control">Save</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>

{% endblock %}

Bachelors project/trading/trading-master/templates/banking/bank_detail_list.html
{% extends 'base.html' %}
{% block bank %}active{% endblock %}
{% block bank_list %}active{% endblock %}
{% block content %}
{% load staticfiles %}
<div class="content-wrapper">
    <section class="content-header">
        <a href="{% url 'bank:debit' pk=bank.id %}"><button type="button" value="Create" class="btn btn-success">Debit</button></a>
        <a href="{% url 'bank:credit' pk=bank.id %}"><button type="button" value="Create" class="btn btn-danger">Credit</button></a>
        <ol class="breadcrumb">
            <li><a href="{% url 'common:index' %}"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="{% url 'bank:list' %}"> Bank List</a></li>
            <li class="active">Bank Detail</li>
        </ol>
    </section>
    <section class="content">
        <div class="row">
            <div class="col-md-12">
                <div class="box">
                    <div class="box-header">
                        <h3 class="text-center"><b>{{bank.name}}|</b> <small><b>Bank Detail List</b></small></h3>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <div class="col-md-4 pull-left">
                                <input type="date" class="form-control date_search" placeholder="Search by Date ..." >
                            </div>
                            <div class="col-md-2 pull-right">
                                <button class="form-control btn btn-primary search">Search</button>
                            </div>
                        <br><br>
                        <hr>
                        </div>
                    </div>
                    <div class="box-body">
                        <div class="table-responsive">
                            <table class="table align-items-center table-striped table-bordered table-hover">
                                <thead class="thead-dark">
                                <tr>
                                    <th>Date</th>
                                    <th>Invoice</th>
                                    <th>Details</th>
                                    <th>Debit Amount</th>
                                    <th>Credit Amount</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for bank in object_list %}
                                <tr>
                                    {% load humanize %}
                                    <td>{{bank.date}}</td>
                                    <td>{{bank.invoice.id|stringformat:"07d"}}</td>
                                    <td>{{bank.description}}</td>
                                    <td>{{bank.debit|floatformat:-2|intcomma}}</td>
                                    <td>{{bank.credit|floatformat:-2|intcomma}}</td>
                                </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                            {% if paginator.page_range|length > 1 %}
                            <div class="text-center col-lg-12">
                                <ul class="pagination justify-content-center">
                                    <li><a  style="background-color: #3070A8; color: white" class="page_previous" href="{% if page_obj.has_previous %}{% url 'bank:detail_list' pk=bank.id %}?page={{ page_obj.previous_page_number }}{% else %}#{% endif %}" title="Previous"><<</a></li>
                                    <li><a style="background-color: #3070A8; color: white" class="page_next" href="{% if page_obj.has_next %}{% url 'bank:detail_list' pk=bank.id %}?page={{ page_obj.next_page_number }}{% else %}#{% endif %}" title="Next">>></a></li>
                                </ul>
                            </div>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>
{% endblock %}

{% block script %}
    {{ block.super }}
<script>
$(function () {
    $('.search').on('click', function () {
        var url = '{% url "bank:detail_list" pk=bank.id %}';
        window.location.href  = url + '?' + 'date=' + $('.date_search').val();
    });
})
</script>
{% endblock %}

Bachelors project/trading/trading-master/templates/banking/bank_list.html
{% extends 'base.html' %}
{% block bank %}active{% endblock %}
{% block bank_list %}active{% endblock %}
{% block content %}
{% load staticfiles %}
<div class="content-wrapper">
    <section class="content-header">
        <ol class="breadcrumb">
            <li><a href="{% url 'common:index' %}"><i class="fa fa-dashboard"></i> Home</a></li>
            <li class="active">Bank List</li>
        </ol>
    </section>
    <br>
    <section class="content">
        <div class="row">
            <div class="col-md-12">
                <div class="box">
                    <div class="box-header">
                        <h3 class="text-center "><b>Bank List</b></h3>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <div class="col-md-4 pull-left">
                                <input type="text" class="form-control name_search" placeholder="Search by Bank Name ..." >
                            </div>
                            <div class="col-md-4">
                                <input type="text" class="form-control account_search" placeholder="Search by Account No ...">
                            </div>
                            <div class="col-md-2 pull-right">
                                <button class="form-control btn btn-primary search">Search</button>
                            </div>
                            <br><br>
                        <hr>
                        </div>
                    </div>
                    <div class="box-body">
                        <div class="table-responsive">
                            <table class="table align-items-center table-striped table-bordered table-hover">
                                <thead class="thead-dark">
                                <tr>
                                    <th>Bank Name</th>
                                    <th>Bank Branch</th>
                                    <th>Account number</th>
                                    <th>Balance</th>
                                    <th class="text-center">Action</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for bank in object_list %}
                                <tr>
                                    <td>{{bank.name|title}}</td>
                                    <td>{{bank.branch|title}}</td>
                                    <td>{{bank.account_number}}</td>
                                    <td>{{ bank.bank_balance|floatformat:-2 }}</td>
                                    <td class="text-center">
                                        <a href="{% url 'bank:update' pk=bank.id %}"><button class="btn btn-primary btn-xs">Update</button></a>
                                        <a href="{% url 'bank:detail_list' pk=bank.id %}"><button class="btn btn-success btn-xs">Details</button></a>
                                    </td>
                                </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                            {% if paginator.page_range|length > 1 %}
                                <div class="text-center">
                                    <ul class="pagination">
                                        <li><a  style="background-color: #3070A8; color: white" class="page_previous" href="{% if page_obj.has_previous %}{% url 'bank:list' %}?page={{ page_obj.previous_page_number }}{% else %}#{% endif %}" title="Previous"><<</a></li>
                                        <li><a style="background-color: #3070A8; color: white" class="page_next" href="{% if page_obj.has_next %}{% url 'bank:list' %}?page={{ page_obj.next_page_number }}{% else %}#{% endif %}" title="Next">>></a></li>
                                    </ul>
                                </div>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>
{% endblock %}

{% block script %}
    {{ block.super }}
<script>
$(function () {
    $('.search').on('click', function () {
        var url = '{% url "bank:list" %}';
        window.location.href  = url + '?' + 'bank_name=' + $('.name_search').val() + '&account_no=' +  $('.account_search').val();
    });
})
</script>

<script>
$('#invoice').on('click', function() {
    var $this = $(this);
  $this.button('loading');
    setTimeout(function() {
       $this.button('reset');
   }, 5000);
});

</script>
{% endblock %}

Bachelors project/trading/trading-master/templates/banking/credit.html
{% extends 'base.html' %}
{% block bank %}active{% endblock %}
{% block bank_list %}active{% endblock %}
{% block content %}
{% load staticfiles %}

<div class="content-wrapper">
    <section class="content-header">
        <ol class="breadcrumb">
            <li><a href="{% url 'common:index' %}"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="{% url 'bank:detail_list' pk=bank.id %}">Bank Detail</a></li>
            <li class="active">Add Credit</li>
        </ol>
    </section>
    <br>
    <section class="content">
        <div class="row">
            <div class="col-md-6 pull-left">
                <div class="box">
                    <div class="box-header">
                        <h3 class="text-center"><b>{{ bank.name|title }} |</b> <small><b>Add Credit Amount</b></small></h3>
                    </div>
                    <div class="box-body">
                        <form action="{% url 'bank:debit' pk=bank.id %}" method="post" autocomplete="off">
                            {% csrf_token %}
                            <div class="row">
                                <input type="hidden" name="bank" value="{{bank.id}}">
                                <div class="col-md-12 pull-left form-group">
                                    <label class="form-control-label">Credit Amount <span style="color:red">*</span></label>
                                    <input type="text" name="credit" class="form-control form-control-alternative" placeholder="Credit Amount" required>
                                </div>
                                <div class="col-md-12 pull-left form-group">
                                    <label class="form-control-label">Date <span style="color:red">*</span></label>
                                    <input type="date" name="date" class="form-control" required>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12 pull-left form-group">
                                    <label class="form-control-label">Detail <span style="color:red">*</span></label>
                                    <input type="text" name="description" class="form-control form-control-alternative" placeholder="Detail" required>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-4 pull-right form-group">
                                    <label class="form-control-label"></label>
                                    <button type="submit" value="Create" class="btn btn-primary form-control">Save</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>

{% endblock %}

Bachelors project/trading/trading-master/templates/banking/debit.html
{% extends 'base.html' %}
{% block bank %}active{% endblock %}
{% block bank_list %}active{% endblock %}
{% block content %}
{% load staticfiles %}
<div class="content-wrapper">
    <section class="content-header">
        <ol class="breadcrumb">
            <li><a href="{% url 'common:index' %}"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="{% url 'bank:detail_list' pk=bank.id %}">Bank Detail</a></li>
            <li class="active">Add Debit</li>
        </ol>
    </section>
    <br>
    <section class="content">
        <div class="row">
            <div class="col-md-6 pull-left">
                <div class="box">
                    <div class="box-header">
                        <h3 class="text-center"><b>{{ bank.name|title }} |</b> <small><b>Add Debit Amount</b></small></h3>
                    </div>
                    <div class="box-body">
                        <form action="{% url 'bank:debit' pk=bank.id %}" method="post" autocomplete="off">
                            {% csrf_token %}
                            <div class="row">
                                <input type="hidden" name="bank" value="{{bank.id}}">
                                <div class="col-md-12 pull-left form-group">
                                    <label class="form-control-label">Debit Amount <span style="color:red">*</span></label>
                                    <input type="text" name="debit" class="form-control form-control-alternative" placeholder="Debit Amount" required>
                                </div>
                                <div class="col-md-12 pull-left form-group">
                                    <label class="form-control-label">Date <span style="color:red">*</span></label>
                                    <input type="date" name="date" class="form-control" required>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12 pull-left form-group">
                                    <label class="form-control-label">Details <span style="color:red">*</span></label>
                                    <textarea type="text" name="description" class="form-control form-control-alternative" placeholder="Details" required></textarea>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-4 pull-right form-group">
                                    <label class="form-control-label"></label>
                                    <button type="submit" value="Create" class="btn btn-primary form-control">Save</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>
{% endblock %}

Bachelors project/trading/trading-master/templates/banking/update_add_bank_list.html
{% extends 'base.html' %}
{% block bank %}active{% endblock %}
{% block bank_list %}active{% endblock %}
{% block content %}
{% load staticfiles %}

<div class="content-wrapper">
    <section class="content-header">

        <ol class="breadcrumb">
            <li><a href="{% url 'common:index' %}"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="{% url 'bank:list' %}">Bank List</a></li>
            <li class="active">Update Bank</li>
        </ol>
    </section>
    <br>
    <section class="content">
        <div class="row">
            <div class="col-md-6 pull-left">
                <div class="box">
                    <div class="box-header">
                        <h3 class="text-center"><b>Update Bank</b></h3>
                    </div>
                    <div class="box-body">
                        <form action="{% url 'bank:update' pk=object.id %}" method="post" autocomplete="off">
                            {% csrf_token %}
                            <div class="row">
                                <div class="col-md-12 pull-left form-group">
                                    <label class="form-control-label">Bank Name <span style="color:red">*</span></label>
                                    <input type="text" name="name" class="form-control form-control-alternative" placeholder="Bank Name" value="{{ object.name }}" required>
                                </div>
                                <div class="col-md-12 pull-left form-group">
                                    <label class="form-control-label">Bank Branch <span style="color:red">*</span></label>
                                    <input type="text" name="branch" class="form-control form-control-alternative" placeholder="Bank Branch" value="{{ object.branch }}" required>
                                </div>
                                <div class="col-md-12 pull-left form-group">
                                    <label class="form-control-label">Account Number <span style="color:red">*</span></label>
                                    <input type="text" name="account_number" class="form-control form-control-alternative" placeholder="Account Number" value="{{ object.account_number }}" required>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-4 pull-right form-group">
                                    <label class="form-control-label"></label>
                                    <button type="submit" value="Create" class="btn btn-primary form-control">Save</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>

{% endblock %}

Bachelors project/trading/trading-master/templates/banking/update_credit.html
{% extends 'base.html' %}
{% block bank %}active{% endblock %}
{% block bank_list %}active{% endblock %}
{% block content %}
{% load staticfiles %}

<div class="content-wrapper">
    <section class="content-header">
        <ol class="breadcrumb">
            <li><a href="{% url 'common:index' %}"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="{% url 'bank:detail_list' pk=object.bank.id %}">Bank Detail</a></li>
            <li class="active">Update Credit</li>
        </ol>
    </section>
    <br>
    <section class="content">
        <div class="row">
            <div class="col-md-6 pull-left">
                <div class="box">
                    <div class="box-header">
                        <h3 class="text-center"><b>Update Debit</b></h3>
                    </div>
                    <div class="box-body">
                        <form action="" method="post" autocomplete="off">
                            {% csrf_token %}
                            <input type="hidden" name="bank" value="{{object.bank.id}}">
                            <div class="row">
                                <div class="col-md-12 pull-left form-group">
                                    <label class="form-control-label">Credit Amount <span style="color:red">*</span></label>
                                    <input type="text" name="credit" class="form-control form-control-alternative" placeholder="Credit Amount" value="{{ object.credit }}" required>
                                </div>
                                <div class="col-md-12 pull-left form-group">
                                    <label class="form-control-label">Date <span style="color:red">*</span></label>
                                    <input type="date" name="date" class="form-control form-control-alternative" placeholder="Date" onfocus="(this.type='date')" onblur="(this.type='text')" required>
                                </div>
                                <div class="col-md-12 pull-left form-group">
                                    <label class="form-control-label">Details <span style="color:red">*</span></label>
                                    <input type="text" name="description" class="form-control form-control-alternative" placeholder="Details" value="{{ object.description }}" required>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-4 pull-right form-group">
                                    <label class="form-control-label"></label>
                                    <button type="submit" value="Create" class="btn btn-primary form-control">Save</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>

{% endblock %}

Bachelors project/trading/trading-master/templates/banking/update_debit.html
{% extends 'base.html' %}
{% block bank %}active{% endblock %}
{% block bank_list %}active{% endblock %}
{% block content %}
{% load staticfiles %}

<div class="content-wrapper">
    <section class="content-header">
        <ol class="breadcrumb">
            <li><a href="{% url 'common:index' %}"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="{% url 'bank:detail_list' pk=object.bank.id %}">Bank Detail</a></li>
            <li class="active">Update Debit</li>
        </ol>
    </section>
    <br>
    <section class="content">
        <div class="row">
            <div class="col-md-6 pull-left">
                <div class="box">
                    <div class="box-header">
                        <h3 class="text-center"><b>Update Debit</b></h3>
                    </div>
                    <div class="box-body">
                        <form action="" method="post" autocomplete="off">
                            {% csrf_token %}
                            <input type="hidden" name="bank" value="{{object.bank.id}}">
                            <div class="row">
                                <div class="col-md-12 pull-left form-group">
                                    <label class="form-control-label">Debit Amount <span style="color:red">*</span></label>
                                    <input type="text" name="debit" class="form-control form-control-alternative" placeholder="Debit Amount" value="{{ object.debit }}" required>
                                </div>
                                <div class="col-md-12 pull-left form-group">
                                    <label class="form-control-label">Date <span style="color:red">*</span></label>
                                    <input type="date" name="date" class="form-control form-control-alternative" placeholder="Date" onfocus="(this.type='date')" onblur="(this.type='text')" required>
                                </div>
                                <div class="col-md-12 pull-left form-group">
                                    <label class="form-control-label">Details <span style="color:red">*</span></label>
                                    <input type="text" name="description" class="form-control form-control-alternative" placeholder="Details" value="{{ object.description }}" required>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-4 pull-right form-group">
                                    <label class="form-control-label"></label>
                                    <button type="submit" value="Create" class="btn btn-primary form-control">Save</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>

{% endblock %}